# Generated by Django 4.2.1 on 2023-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('CS', 'CS'), ('IS', 'IS'), ('DS', 'DS'), ('AI', 'AI'), ('IT', 'IT')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='nationalid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
