# Generated by Django 4.2.1 on 2023-05-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_level_alter_student_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Harry James Potter', max_length=50)),
                ('email', models.CharField(default='potter@gmail.com', max_length=100)),
                ('phone', models.CharField(default='01234567890', max_length=20)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('password', models.CharField(default='MUFFLIATO', max_length=20)),
            ],
        ),
    ]
