# Generated by Django 4.2.1 on 2023-05-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Algerian', 'Algerian'), ('Bahraini', 'Bahraini'), ('Comorian', 'Comorian'), ('Djiboutian', 'Djiboutian'), ('Egyptian', 'Egyptian'), ('Emirati', 'Emirati'), ('Iraqi', 'Iraqi'), ('Jordanian', 'Jordanian'), ('Kuwaiti', 'Kuwaiti'), ('Lebanese', 'Lebanese'), ('Libyan', 'Libyan'), ('Mauritanian', 'Mauritanian'), ('Moroccan', 'Moroccan'), ('Omani', 'Omani'), ('Palestinian', 'Palestinian'), ('Qatari', 'Qatari'), ('Saudi Arabian', 'Saudi Arabian'), ('Somali', 'Somali'), ('Sudanese', 'Sudanese'), ('Syrian', 'Syrian'), ('Tunisian', 'Tunisian'), ('Yemeni', 'Yemeni')], max_length=50),
        ),
    ]
