# Generated by Django 4.2.1 on 2023-05-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
